# BlockScanner Default Config

title = "BlockScanner"

[base]
folder = "chaindata"
debug = false

[blockchain]
protocol = "http:"
hostname = "127.0.0.1"
port = 8545
path = "/"

[database]
protocol = "mongodb:"
hostname = "127.0.0.1"
port = 27017
db = "TEST"
prefix = "BS_"
user = "BC2"
password = "password"