# Amoeba Default Config

title = "Amoeba"

[base]
folder = "chaindata"
debug = false

[blockchain]
protocol = "http:"
hostname = "127.0.0.1"
port = 8545
path = "/"

[mysql]
host = "61.66.218.248"
port = 8545
user = "root"
password = "123456"
database = "ioneit"

[mongo]
host = "127.0.0.1"
port = 3306
user = "root"
password = "password"
database = "amoeba"