version: '3'

services:
  amoeba:
    image: amoeba
    container_name: amoeba
    build: .
    environment:
      NODE_ENV: production
    ports:
      - 3000:3000
    depends_on:
      - mongo
      - mysql

  mongo:
    image: mongo
    container_name: mongo
    build: .
    environment:
      NODE_ENV: production
    ports:
      - 27017:27017

  mysql:
    image: mysql:8.0.12
    container_name: mysql
    restart: always
    build: .
    environment:
      MYSQL_ROOT_PASSWORD: amoeba
      MYSQL_DATABASE: amoeba
      MYSQL_USER: amoeba
      MYSQL_PASSWORD: amoeba
    ports:
      - 3306:3306

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    links:
      - mysql
    ports:
      - 8088:80
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
    depends_on:
      - mysql